#TREASURE ISLAND

# print("Welcome to treasure island ")
# direction=input("choose direction").lower()
# if direction=="right":
#     print("game is over")
# if direction=='left':
#     print(" do you want to cross by swim or need to wait for boart ")
#     position=input("choose one")
#     if position =='swim':
#         print("you have been drawn game s over")
#     else:
#         print("you are save and move to next level")
#     color_door=input("choose the color of door")
#     if color_door=='blue':
#         print("you choose the right door you won ")
#     else:
#         print("you loose at final stage try again")
# # else:
#     print("you choose wrong direction")
# if direction=='right':
#      print("you go down to the hole game is over")
# print("Welcome to treasure island")
# direction = input("Choose a direction: ").lower()
# if direction == "right":
#     print("You go down into the hole. Game over.")


# print("welocme to rollercoster")
# height=int(input("what is your height"))
# if height>12:
#     print("you are welcome")
# else:
#     print("you are not fit to ride roller coster")

# number=int(input("what is the number"))
# if number%2==0:
#     print("the number is even")
# else:
#     print("the number is odd")
    
# print("welcome to park")
# height=int(input("wht is the height"))
# age=int(input("what is your age"))
# if height >12 :
#     if age >18:
#         print("you are eligible")
#     elif age==10:
#         print("your age is match")
#     else:
#         print("your age is not enough to perform")
# else :
#     print("you are not eligible")
# height=float(input("wht is the height"))
# weight=int(input("what is your weight"))
# BMI=weight/height**2
# print(f'your BMI is {BMI} and ')
# if BMI>18.5:
#     # print("you are underwright")
#     if BMI<25:
#         print("you are normal weight")
#     elif BMI<30:
#         print("you are slightly overweight ")
#     elif BMI<35:
#         print("you are obese")
#     else:
#         print("you are over wreight")
    
#leap year
# year=int(input("write a year that is leap year or not"))
# if year%4==0: 
#     if year%100==0:        
#        if year%400==0:
#           print("year is leap year")
#        else:
#            print("not leap year")
#     else:
#         print("leap year")
# else:
#     print("year is not leap year")
# print("you are in rolller coaster")
# height=float(input("what is your height"))
# # age=int(input("what is your weight "))
# if height>12:
#     print("you can ride")
#     age=int(input("what is your age"))
#     if age<12:
#         print("you have to pay $5")
#     elif  age <18:
#         print("you have to pay 7$")
#     else:
#         print("you have to pay 12$")
#     photos=str(input("do you want photos"))
#     if photos =='yes':
#         print("you have to pay extra 5$")
# else:
#     print("you cant ride")
        
#PIZZA ORDER PRACTICE
# print("what you like to order")
# order = (input("small,medium or large"))
# pepperoni=(input("do you like to have some extra pepperoni"))
# bills=0
# if order=='small':
#     bills=5     
# elif order=='medium':
#     bills=15
# else:
#     bills=25
# if pepperoni =='yes':
#     if order=='small':
#         bills +=2
#     else:
#         bills += 3
# print(f'your bills is {bills}')

#OPERATOR CONDITION
# love calculator
# print('welocme to love calculator')
# name1=input("write 1st person name")
# name2=input("write 2nd person name")
# combined_name=name1+name2 
# lower_case =combined_name.lower()
# t=lower_case.count('t')
# r=lower_case.count('r')
# u=lower_case.count('u')
# e=lower_case.count('e')
# first_digit=t+r+u+e

# l=lower_case.count('l')
# o=lower_case.count('o')
# v=lower_case.count('v')
# e=lower_case.count('e')

# second_digit=l+o+v+e
# score=str(first_digit)+str(second_digit)
# if score>75 and score<99:
#     print("your are made for each other")
# elif score<75 and score>30:
#     print("good enough")
# else:
#     print("you are not made for each other")

#TREASURE ISLAND

print("Welcome to treasure island ")
direction=input("choose direction").lower()
if direction=="right":
    print("game is over")
if direction=='left':
    print(" do you want to cross by swim or need to wait for boart ")
    position=input("choose one")
    if position =='swim':
        print("you have been drawn game s over")
    else:
        print("you are save and move to next level")
    color_door=input("choose the color of door")
    if color_door=='blue':
        print("you choose the right door you won ")
    else:
        print("you loose at final stage try again")
# else:
#     print("you choose wrong direction")
# if direction=='right':
#      print("you go down to the hole game is over")
# print("Welcome to treasure island")
# direction = input("Choose a direction: ").lower()
# if direction == "right":
#     print("You go down into the hole. Game over.")
